export const Accordion = {
  type: 'Accordion',
  variable: {
    textColor: {
      type: 'color',
      label: '标题文本颜色',
      groupsName: '标题',
    },
    lineHeight: {
      type: 'px',
      label: '标题文本行高',
      groupsName: '标题',
    },
    fontSize: {
      type: 'px',
      label: '标题文本尺寸',
      groupsName: '标题',
    },
    fontWeight: {
      type: 'select',
      label: '标题文本字重',
      groupsName: '标题',
      options: [
        { title: '100', value: '100' },
        { title: '200', value: '200' },
        { title: '300', value: '300' },
        { title: '400', value: '400' },
        { title: '500', value: '500' },
      ],
    },

    backgroundColor: {
      type: 'color',
      label: '头部背景颜色',
      groupsName: '背景颜色',
    },
    titleColor: {
      type: 'color',
      label: '装饰条颜色',
      groupsName: '标题',
    },
    lineColor: {
      type: 'color',
      label: '分割线颜色',
      groupsName: '边框',
    },
    tagSize: { type: 'px', label: '标题装饰图标尺寸', groupsName: '标题' },
    tagMargin: { type: 'px', label: '符号右外边距', groupsName: '标题' },
    arrowColor: {
      type: 'color',
      label: '后缀图标颜色',
      groupsName: '标题',
    },
    arrowSize: { type: 'px', label: '后缀图标尺寸', groupsName: '标题' },
    bodyBgColor: {
      type: 'color',
      label: '内容背景颜色',
      groupsName: '背景颜色',
    },
    borderColor: { type: 'color', label: '边框颜色', groupsName: '边框' },
    borderRadius: { type: 'px', label: '边框圆角', groupsName: '边框' },
  },
  groupsName: '容器',
  icon: 'icon-ico-comp-app-Accordion',
  title: '折叠面板',
  defaultValue: [
    {
      textColor: 'rgb(28, 36, 46)',
      lineHeight: '100%',
      fontSize: '16px',
      fontWeight: '400',
      backgroundColor: '#fff',
      titleColor: '#47e',
      lineColor: '#f0f0f0',
      tagSize: '16px',
      tagMargin: '6px',
      arrowColor: '#cccccc',
      arrowSize: '19px',
      bodyBgColor: '#fff',
      borderColor: '#DDD',
      borderRadius: '4px',
    },
  ],
  tpl: `
  .lcdp-accordion .lcdp-accordion-header{
    color: textColor;
    font-weight: fontWeight;
    font-size: fontSize;
    line-height: lineHeight;
    background: backgroundColor;
  }
  .lcdp-accordion-header-default-icon{
    height: tagSize;
    background: titleColor;
    margin-right: tagMargin;
  }
  .adm-list-item-content{
    border-color: lineColor;
  }

  .lcdp-accordion .adm-collapse-arrow  svg{
    color: arrowColor;
    width:  arrowSize;
    height: arrowSize;
  }
  .lcdp-accordion .adm-list-item-content-main{
    background: bodyBgColor;
  }
  .lcdp-accordion{
    .adm-collapse{
      border-radius: borderRadius;
      border-color: borderColor !important;
    }
  }`,
  components: [
    {
      id: 'Accordion_960849',
      label: '折叠面板',
      compName: 'Accordion',
      type: 'Accordion',
      compType: 0,
      compLib: '@/components',
      props: {
        name: '折叠面板',
        visible: 1,
        bordered: true,
        accordion: true,
        data: [],
        cardIconType: 'middle',
        defaultActiveKey: ['1'],
      },
      style: {},
      isContainer: true,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'h5',
      description: '',
      image: '',
      groupsName: '容器',
      icon: 'Accordion',
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [
        {
          id: 'AccordionPanel_530736',
          label: '折叠子面板',
          compName: 'AccordionPanel',
          type: 'AccordionPanel',
          compType: 0,
          compLib: '@/components',
          props: {
            name: '折叠子面板',
            visible: true,
            header: '显示边框',
            key: '1',
          },
          style: {},
          isContainer: true,
          isBusiObjContainer: false,
          cmdgroup: ['basic'],
          platform: 'h5',
          engineApi: ['downloadFileByFileCode'],
          description: '',
          image: '',
          groupsName: '容器',
          icon: 'Accordion',
          setEvents: [],
          isLabelDropBoxChild: false,
          components: [
            {
              id: 'Text_108729',
              label: '文本',
              compName: 'Text',
              type: 'Text',
              compType: 1,
              compLib: 'antd-mobile',
              props: {
                name: '内容文本',
              },
              style: {},
              isContainer: false,
              isBusiObjContainer: false,
              cmdgroup: ['basic'],
              platform: 'h5',
              fieldProps: {
                trigger: 'onChange',
                valuePropName: 'children',
              },
              isInlineBlock: true,
              setEvents: [],
              icon: 'Text',
              description: '',
              image: '',
              groupsName: '基础',
              transform: {
                value: 'children',
              },
              isLabelDropBoxChild: false,
              components: [],
              path: [
                '769713',
                'View_769713_1',
                'Accordion_960849',
                'AccordionPanel_530736',
              ],
            },
          ],
          path: ['769713', 'View_769713_1', 'Accordion_960849'],
        },
        {
          id: 'AccordionPanel_9734406',
          label: '折叠子面板',
          compName: 'AccordionPanel',
          type: 'AccordionPanel',
          compType: 0,
          compLib: '@/components',
          props: {
            name: '折叠子面板',
            visible: true,
            header: '标题2',
            key: '2',
          },
          style: {},
          isContainer: true,
          isBusiObjContainer: false,
          cmdgroup: ['basic'],
          platform: 'h5',
          engineApi: ['downloadFileByFileCode'],
          description: '',
          image: '',
          groupsName: '容器',
          icon: 'Accordion',
          setEvents: [],
          isLabelDropBoxChild: false,
          components: [
            {
              id: 'Text_337264',
              label: '文本',
              compName: 'Text',
              type: 'Text',
              compType: 1,
              compLib: 'antd-mobile',
              props: {
                name: '内容文本',
              },
              style: {},
              isContainer: false,
              isBusiObjContainer: false,
              cmdgroup: ['basic'],
              platform: 'h5',
              fieldProps: {
                trigger: 'onChange',
                valuePropName: 'children',
              },
              isInlineBlock: true,
              setEvents: [],
              icon: 'Text',
              description: '',
              image: '',
              groupsName: '基础',
              transform: {
                value: 'children',
              },
              isLabelDropBoxChild: false,
              components: [],
              path: [
                '769713',
                'View_769713_1',
                'Accordion_960849',
                'AccordionPanel_9734406',
              ],
            },
          ],
          path: ['769713', 'View_769713_1', 'Accordion_960849'],
        },
      ],
      path: ['769713', 'View_769713_1'],
    },
    {
      id: 'View_519882',
      label: '普通容器',
      compName: 'View',
      type: 'View',
      compType: 0,
      compLib: 'custom',
      props: {
        name: '普通容器1',
        basicStatus: 1,
      },
      style: {
        textAlign: 'left',
        display: 'block',
        flexDirection: 'column',
        padding: '0px 0px 0px 0px',
        width: '100%',
        backgroundColor: '#FFFFFF',
        height: '50px',
      },
      isContainer: true,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'View',
      description: '',
      image: '',
      groupsName: '布局',
      engineApi: ['service.downloadFileByFileCode'],
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['998509'],
    },
    {
      id: 'Accordion_960849',
      label: '折叠面板',
      compName: 'Accordion',
      type: 'Accordion',
      compType: 0,
      compLib: '@/components',
      props: {
        name: '折叠面板',
        visible: 1,
        bordered: false,
        accordion: true,
        data: [],
        cardIconType: 'middle',
        defaultActiveKey: ['1'],
      },
      style: {},
      isContainer: true,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'h5',
      description: '',
      image: '',
      groupsName: '容器',
      icon: 'Accordion',
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [
        {
          id: 'AccordionPanel_530736',
          label: '折叠子面板',
          compName: 'AccordionPanel',
          type: 'AccordionPanel',
          compType: 0,
          compLib: '@/components',
          props: {
            name: '折叠子面板',
            visible: true,
            header: '标题1',
            key: '1',
          },
          style: {},
          isContainer: true,
          isBusiObjContainer: false,
          cmdgroup: ['basic'],
          platform: 'h5',
          engineApi: ['downloadFileByFileCode'],
          description: '',
          image: '',
          groupsName: '容器',
          icon: 'Accordion',
          setEvents: [],
          isLabelDropBoxChild: false,
          components: [
            {
              id: 'Text_108729',
              label: '文本',
              compName: 'Text',
              type: 'Text',
              compType: 1,
              compLib: 'antd-mobile',
              props: {
                name: '内容文本',
              },
              style: {
                textAlign: 'left',
                lineHeight: '24px',
                fontSize: 14,
                border: '0px',
              },
              isContainer: false,
              isBusiObjContainer: false,
              cmdgroup: ['basic'],
              platform: 'h5',
              fieldProps: {
                trigger: 'onChange',
                valuePropName: 'children',
              },
              isInlineBlock: true,
              setEvents: [],
              icon: 'Text',
              description: '',
              image: '',
              groupsName: '基础',
              transform: {
                value: 'children',
              },
              isLabelDropBoxChild: false,
              components: [],
              path: [
                '769713',
                'View_769713_1',
                'Accordion_960849',
                'AccordionPanel_530736',
              ],
            },
          ],
          path: ['769713', 'View_769713_1', 'Accordion_960849'],
        },
        {
          id: 'AccordionPanel_9734406',
          label: '折叠子面板',
          compName: 'AccordionPanel',
          type: 'AccordionPanel',
          compType: 0,
          compLib: '@/components',
          props: {
            name: '折叠子面板',
            visible: true,
            header: '标题2',
            key: '2',
          },
          style: {},
          isContainer: true,
          isBusiObjContainer: false,
          cmdgroup: ['basic'],
          platform: 'h5',
          engineApi: ['downloadFileByFileCode'],
          description: '',
          image: '',
          groupsName: '容器',
          icon: 'Accordion',
          setEvents: [],
          isLabelDropBoxChild: false,
          components: [
            {
              id: 'Text_337264',
              label: '文本',
              compName: 'Text',
              type: 'Text',
              compType: 1,
              compLib: 'antd-mobile',
              props: {
                name: '内容文本',
              },
              style: {
                textAlign: 'left',
                lineHeight: '24px',
                fontSize: 14,
                border: '0px',
              },
              isContainer: false,
              isBusiObjContainer: false,
              cmdgroup: ['basic'],
              platform: 'h5',
              fieldProps: {
                trigger: 'onChange',
                valuePropName: 'children',
              },
              isInlineBlock: true,
              setEvents: [],
              icon: 'Text',
              description: '',
              image: '',
              groupsName: '基础',
              transform: {
                value: 'children',
              },
              isLabelDropBoxChild: false,
              components: [],
              path: [
                '769713',
                'View_769713_1',
                'Accordion_960849',
                'AccordionPanel_9734406',
              ],
            },
          ],
          path: ['769713', 'View_769713_1', 'Accordion_960849'],
        },
      ],
      path: ['769713', 'View_769713_1'],
    },
  ],
};
