export const Divider = {
  type: 'Divider',
  variable: {
    textColor: { type: 'color', label: '分割线颜色', groupsName: '文字' },
  },
  groupsName: '基础',
  icon: 'icon-ico-comp-divider',
  title: '分割线',
  defaultValue: [{}],
  tpl: ``,
  components: [
    {
      id: 'Divider_0510467',
      label: '分割线',
      compName: 'Divider',
      type: 'Divider',
      compType: 1,
      compLib: '@/components',
      props: {
        name: '分割线',
        visible: 1,
        type: 'horizontal',
        dashed: false,
        dashedWidth: 4,
        dashedMargin: 4,
        showTitle: false,
        dividerText: '标题',
        orientation: 'center',
        titleColor: 'rgba(28,36,46,0.75)',
        titleFontSize: 14,
        titleFontWeight: 400,
        contentPosition: 'center',
      },
      style: {
        margin: '12px 0 12px 0',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'h5',
      icon: 'Divider',
      description: '',
      image: '',
      groupsName: '基础',
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['769713', 'View_769713_1'],
    },
    {
      id: 'Divider_0510467',
      label: '分割线',
      compName: 'Divider',
      type: 'Divider',
      compType: 1,
      compLib: '@/components',
      props: {
        name: '分割线',
        visible: 1,
        type: 'vertical',
        dashed: false,
        dashedWidth: 4,
        dashedMargin: 4,
        showTitle: false,
        dividerText: '标题',
        orientation: 'center',
        titleColor: 'rgba(28,36,46,0.75)',
        titleFontSize: 14,
        titleFontWeight: 400,
        contentPosition: 'center',
      },
      style: {
        margin: '12px 0 12px 0',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'h5',
      icon: 'Divider',
      description: '',
      image: '',
      groupsName: '基础',
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['769713', 'View_769713_1'],
    },
  ],
};
