export const DMultiplePicker = {
    type: 'DMultiplePicker',
    variable: {
      iconColor: {
        type: 'color',
        label: '后缀图标颜色',
        groupsName: '图标',
        desc: '继承自表单，此处不可编辑',
        canEdit: false,
        extendsKey: 'DForm',
      },
      iconSize: { type: 'px', label: '后缀图标尺寸', groupsName: '图标', desc: '继承自表单，此处不可编辑',
      labelTextColor: {
        type: 'color',
        label: '标签文本颜色',
        groupsName: '标签',
        desc: '继承自表单，此处不可编辑',
        canEdit: false,
        extendsKey: 'DForm',
      },
      labelLineHeight: {
        type: 'px',
        label: '标签文本行高',
        groupsName: '标签',
        desc: '继承自表单，此处不可编辑',
        canEdit: false,
        extendsKey: 'DForm',
      },
      labelFontSize: {
        type: 'px',
        label: '标签文本尺寸',
        groupsName: '标签',
        desc: '继承自表单，此处不可编辑',
        canEdit: false,
        extendsKey: 'DForm',
      },
      labelFontWeight: {
        type: 'select',
        label: '标签文本字重',
        groupsName: '标签',
        options: [
          { title: '100', value: '100' },
          { title: '200', value: '200' },
          { title: '300', value: '300' },
          { title: '400', value: '400' },
          { title: '500', value: '500' },
        ],
        desc: '继承自表单，此处不可编辑',
        canEdit: false,
        extendsKey: 'DForm',
      },
      textColor: {
        type: 'color',
        label: '文本颜色',
        groupsName: '组件',
        desc: '继承自表单，此处不可编辑',
        canEdit: false,
        extendsKey: 'DForm',
      },
      fontSize: {
        type: 'px',
        label: '文本尺寸',
        groupsName: '组件',
        desc: '继承自表单，此处不可编辑',
        canEdit: false,
        extendsKey: 'DForm',
      },
      lineHeight: {
        type: 'px',
        label: '文本行高',
        groupsName: '组件',
        desc: '继承自表单，此处不可编辑',
        canEdit: false,
        extendsKey: 'DForm',
      },
      fontWeight: {
        type: 'select',
        label: '文本字重',
        groupsName: '组件',
        options: [
          { title: '100', value: '100' },
          { title: '200', value: '200' },
          { title: '300', value: '300' },
          { title: '400', value: '400' },
          { title: '500', value: '500' },
        ],
        desc: '继承自表单，此处不可编辑',
        canEdit: false,
        extendsKey: 'DForm',
      },
      paddingValue: {
        type: 'marginInput',
        label: '内边距',
        groupsName: '组件',
        desc: '继承自表单，此处不可编辑',
        canEdit: false,
        extendsKey: 'DForm',
      },
      headTextAlign: {
        type: 'select',
        label: '文字对齐方式',
        groupsName: '组件',
        desc: '继承自表单，此处不可编辑',
        canEdit: false,
        extendsKey: 'DForm',
        options: [
          { title: 'left', value: 'left' },
          { title: 'center', value: 'center' },
          { title: 'right', value: 'right' },
        ],
      },
    },
    groupsName: '表单',
    icon: 'icon-ico-comp-app-DMultiplePicker',
    title: '多项选择',
    defaultValue: [
      {
      },
    ],
    tpl: ``,
    components: [
      {
        id: 'DForm_333712',
        label: '表单',
        compName: 'DForm',
        type: 'DForm',
        compType: 2,
        compLib: '@/components',
        props: {
          name: '表单',
          formCode: 'DForm_333712',
          autoLineFeed: true,
          failScroll: true,
          errorFlag: true,
          hiddenBorder: '0',
          itemHasStar: true,
        },
        style: {
          width: 'auto',
        },
        isContainer: true,
        isBusiObjContainer: true,
        cmdgroup: ['basic'],
        platform: 'h5',
        setEvents: [],
        description: '',
        image: '',
        groupsName: '容器',
        icon: 'DForm',
        isLabelDropBoxChild: false,
        components: [
          {
            id: 'DMultiplePicker_919181',
            label: '多项选择',
            compName: 'DMultiplePicker',
            type: 'DMultiplePicker',
            compType: 2,
            compLib: '@/components',
            props: {
              name: '多项选择',
              valueType: 'ellipsis',
              titleIcon: 'none',
              postfix: '',
              postfixIconPosition: 'before',
              title: '多项选择',
              dformType: 'DMultiplePicker',
              positionType: 'horizontal',
              status: '1',
              options: [
                {
                  label: '选项1',
                  value: 'options1',
                  id: 'options1',
                },
                {
                  label: '选项2',
                  value: 'options2',
                  id: 'options2',
                },
              ],
              icon: {
                isIconFont: false,
                theme: 'outlined',
                type: 'right',
              },
              fieldProps: 'fecss',
            },
            style: {},
            isContainer: false,
            isBusiObjContainer: false,
            cmdgroup: ['basic'],
            platform: 'h5',
            fieldProps: {
              trigger: 'onChange',
              valuePropName: 'defaultValue',
            },
            engineApi: ['downloadFileByFileCode', 'getMaterialFile'],
            setEvents: [],
            description: '',
            image: '',
            groupsName: '表单',
            isAppChildForm: true,
            isLabelDropBoxChild: false,
            components: [],
            path: ['769713', 'View_769713_1', 'DForm_458695'],
          },
        ],
        path: ['769713', 'View_769713_1'],
      },
    ],
  };
