export const LoadMore = {
  type: 'LoadMore',
  variable: {
    backgroundColor: {
      type: 'color',
      label: '背景颜色',
      groupsName: '背景颜色',
    },
    borderColor: { type: 'color', label: '边框颜色', groupsName: '边框' },
    borderRadius: { type: 'px', label: '边框圆角', groupsName: '边框' },
  },
  groupsName: '高级',
  icon: 'icon-ico-comp-app-LoadMore',
  title: '动态列表',
  defaultValue: [
    {
      backgroundColor: 'rgba(0,0,0,0)',
      borderColor: 'rgba(0,0,0,0)',
      borderRadius: '0',
    },
  ],
  tpl: `
    .adm-list-item{
      --adm-color-background: backgroundColor;
      border-radius: borderRadius;
      border: 1PX solid borderColor;
    }`,
  components: [
    {
      id: 'DynamicList_686726',
      label: '动态列表',
      compName: 'DynamicList',
      type: 'DynamicList',
      compType: 2,
      compLib: '@/components',
      props: {
        name: '动态列表',
        columnNum: 1,
        status: '1',
        styleType: 'default',
        paging: false,
        pageSize: 1,
        pageNum: 20,
        pulling: false,
        pullingText: '下拉刷新',
        canReleaseText: '松开刷新',
        refreshingText: '正在刷新',
        completeText: '刷新成功',
        dataId: 'das',
        dataSource: '$[{id: 1},{id: 2}, {id: 3}]$',
      },
      style: {
        titleFontSize: 15,
      },
      isContainer: true,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'h5',
      engineApi: ['MemoRenderer'],
      setEvents: [],
      description: '',
      image: '',
      groupsName: '高级',
      icon: 'LoadMore',
      isLabelDropBoxChild: false,
      functors: {
        dataSource: {
          title: '$[{id: 1},{id: 2}, {id: 3}]$',
          value: '$[{  id: 1}, {  id: 2}, {  id: 3}]$',
          dependOtherIds: [],
        },
      },
      components: [
        {
          id: 'View_948063',
          label: '布局容器',
          compName: 'View',
          type: 'View',
          compType: 0,
          compLib: '@/components',
          props: {
            name: '布局容器1',
            visible: 1,
          },
          style: {
            margin: '10px 5px 0 5px',
            padding: '12px 12px 12px 12px',
            borderRadius: 8,
            backgroundColor: 'rgba(255, 255, 255, 1)',
            flexDirection: 'row',
            alignItems: 'center',
            display: 'flex',
          },
          isContainer: true,
          isBusiObjContainer: false,
          cmdgroup: ['basic'],
          platform: 'h5',
          engineApi: ['downloadFileByFileCode'],
          description: '',
          image: '',
          groupsName: '容器',
          icon: 'View',
          setEvents: [],
          isLabelDropBoxChild: false,
          components: [
            {
              id: 'Image_466906',
              label: '图片',
              compName: 'Image',
              type: 'Image',
              compType: 1,
              compLib: '@/components',
              props: {
                name: '图片',
                visible: 'true',
                disabled: true,
                uploadType: 'fileType',
                src: 'https://gw.alipayobjects.com/zos/rmsportal/WXoqXTHrSnRcUwEaQgXJ.png',
                srcType: 'fileCode',
              },
              style: {
                width: '100px',
                height: '76px',
                backgroundColor: 'rgba(0, 0, 0, 0.04)',
              },
              isContainer: false,
              isBusiObjContainer: false,
              cmdgroup: ['basic'],
              platform: 'h5',
              engineApi: ['downloadFileByFileCode', 'downloadByFileId', 'http'],
              isInlineBlock: true,
              setEvents: [],
              description: '',
              image: '',
              groupsName: '基础',
              icon: 'Image',
              isLabelDropBoxChild: false,
              components: [],
              path: [
                '454426',
                'View_454426_1',
                'DynamicList_686726',
                'View_948063',
              ],
            },
            {
              id: 'View_551793',
              label: '布局容器',
              compName: 'View',
              type: 'View',
              compType: 0,
              compLib: '@/components',
              props: {
                name: '布局容器1',
                visible: 1,
              },
              style: {
                flex: 1,
                margin: '0 0 0 9px',
                padding: '0 0 0 0',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'stretch',
              },
              isContainer: true,
              isBusiObjContainer: false,
              cmdgroup: ['basic'],
              platform: 'h5',
              engineApi: ['downloadFileByFileCode'],
              description: '',
              image: '',
              groupsName: '容器',
              icon: 'View',
              setEvents: [],
              isLabelDropBoxChild: false,
              components: [
                {
                  id: 'View_500965',
                  label: '布局容器',
                  compName: 'View',
                  type: 'View',
                  compType: 0,
                  compLib: '@/components',
                  props: {
                    name: '布局容器1',
                    visible: 1,
                  },
                  style: {
                    margin: '0 0 0 0',
                    padding: '0 0 0 0',
                    display: 'flex',
                    flexDirection: 'row',
                  },
                  isContainer: true,
                  isBusiObjContainer: false,
                  cmdgroup: ['basic'],
                  platform: 'h5',
                  engineApi: ['downloadFileByFileCode'],
                  description: '',
                  image: '',
                  groupsName: '容器',
                  icon: 'View',
                  setEvents: [],
                  isLabelDropBoxChild: false,
                  components: [
                    {
                      id: 'Text_70937',
                      label: '文本输入',
                      compName: 'Text',
                      type: 'Text',
                      compType: 1,
                      compLib: 'antd-mobile',
                      props: {
                        name: '标题',
                        children: '列表标题',
                      },
                      style: {
                        fontSize: 14,
                        fontWeidht: 'bold',
                        color: 'rgba(0, 0, 0, 0.9)',
                      },
                      isContainer: false,
                      isBusiObjContainer: false,
                      cmdgroup: ['basic'],
                      platform: 'h5',
                      fieldProps: {
                        trigger: 'onChange',
                        valuePropName: 'children',
                      },
                      isInlineBlock: true,
                      setEvents: [],
                      icon: 'Text',
                      description: '',
                      image: '',
                      groupsName: '基础',
                      transform: {
                        value: 'children',
                      },
                      isLabelDropBoxChild: false,
                      components: [],
                      path: [
                        '454426',
                        'View_454426_1',
                        'DynamicList_686726',
                        'View_948063',
                        'View_551793',
                        'View_500965',
                      ],
                    },
                  ],
                  path: [
                    '454426',
                    'View_454426_1',
                    'DynamicList_686726',
                    'View_948063',
                    'View_551793',
                  ],
                },
                {
                  id: 'View_1620444',
                  label: '布局容器',
                  compName: 'View',
                  type: 'View',
                  compType: 0,
                  compLib: '@/components',
                  props: {
                    name: '布局容器2',
                    visible: 1,
                  },
                  style: {
                    margin: '6px 0 0 0',
                    padding: '0 0 0 0',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'stretch',
                  },
                  isContainer: true,
                  isBusiObjContainer: false,
                  cmdgroup: ['basic'],
                  platform: 'h5',
                  engineApi: ['downloadFileByFileCode'],
                  description: '',
                  image: '',
                  groupsName: '容器',
                  icon: 'View',
                  setEvents: [],
                  isLabelDropBoxChild: false,
                  components: [
                    {
                      id: 'Text_39779957',
                      label: '文本输入',
                      compName: 'Text',
                      type: 'Text',
                      compType: 1,
                      compLib: 'antd-mobile',
                      props: {
                        name: '详情',
                        children:
                          '描述文案内容展示，描述文案内容展示描述文案内容展示内容展示最多展示两行',
                      },
                      style: {
                        color: 'rgba(0, 0, 0, 0.6)',
                        fontSize: 11,
                      },
                      isContainer: false,
                      isBusiObjContainer: false,
                      cmdgroup: ['basic'],
                      platform: 'h5',
                      fieldProps: {
                        trigger: 'onChange',
                        valuePropName: 'children',
                      },
                      isInlineBlock: true,
                      setEvents: [],
                      icon: 'Text',
                      description: '',
                      image: '',
                      groupsName: '基础',
                      transform: {
                        value: 'children',
                      },
                      isLabelDropBoxChild: false,
                      components: [],
                      path: [
                        '454426',
                        'View_454426_1',
                        'DynamicList_686726',
                        'View_948063',
                        'View_551793',
                        'View_1620444',
                      ],
                    },
                  ],
                  path: [
                    '454426',
                    'View_454426_1',
                    'DynamicList_686726',
                    'View_948063',
                    'View_551793',
                  ],
                },
                {
                  id: 'View_874017',
                  label: '布局容器',
                  compName: 'View',
                  type: 'View',
                  compType: 0,
                  compLib: '@/components',
                  props: {
                    name: '布局容器3',
                    visible: 1,
                  },
                  style: {
                    margin: '6px 0 0 0',
                    padding: '0 0 0 0',
                    display: 'flex',
                    flexDirection: 'row',
                    justifyContent: 'space-between',
                  },
                  isContainer: true,
                  isBusiObjContainer: false,
                  cmdgroup: ['basic'],
                  platform: 'h5',
                  engineApi: ['downloadFileByFileCode'],
                  description: '',
                  image: '',
                  groupsName: '容器',
                  icon: 'View',
                  setEvents: [],
                  isLabelDropBoxChild: false,
                  components: [
                    {
                      id: 'View_293786',
                      label: '布局容器',
                      compName: 'View',
                      type: 'View',
                      compType: 0,
                      compLib: '@/components',
                      props: {
                        name: '布局容器1',
                        visible: 1,
                      },
                      style: {
                        margin: '0 0 0 0',
                        padding: '0 0 0 0',
                        display: 'flex',
                        flexDirection: 'row',
                      },
                      isContainer: true,
                      isBusiObjContainer: false,
                      cmdgroup: ['basic'],
                      platform: 'h5',
                      engineApi: ['downloadFileByFileCode'],
                      description: '',
                      image: '',
                      groupsName: '容器',
                      icon: 'View',
                      setEvents: [],
                      isLabelDropBoxChild: false,
                      components: [
                        {
                          id: 'Icon_460385',
                          label: '图标',
                          compName: 'Icon',
                          type: 'Icon',
                          compType: 1,
                          compLib: '@/components',
                          props: {
                            name: '图标',
                            state: '1',
                            mode: 'normal',
                            icon: {
                              type: 'check-circle',
                              theme: 'outlined',
                              fontAddress: '',
                              isIconFont: false,
                            },
                            size: 'sm',
                            theme: 'outlined',
                            type: {
                              type: 'eye',
                              theme: 'filled',
                              fontAddress: '',
                              isIconFont: false,
                              iconFileInfo: {},
                            },
                          },
                          style: {
                            border: '0px',
                            color: '#9b9b9b',
                            fontSize: 12,
                            margin: '0 3 0 0',
                          },
                          isContainer: false,
                          isBusiObjContainer: false,
                          cmdgroup: ['basic'],
                          platform: 'h5',
                          engineApi: [
                            'downloadFileByFileCode',
                            'getMaterialFile',
                          ],
                          isInlineBlock: true,
                          setEvents: [],
                          description: '',
                          image: '',
                          groupsName: '基础',
                          icon: 'Icon',
                          isLabelDropBoxChild: false,
                          components: [],
                          path: [
                            '454426',
                            'View_454426_1',
                            'DynamicList_686726',
                            'View_948063',
                            'View_551793',
                            'View_874017',
                            'View_293786',
                          ],
                        },
                        {
                          id: 'Text_047284',
                          label: '文本输入',
                          compName: 'Text',
                          type: 'Text',
                          compType: 1,
                          compLib: 'antd-mobile',
                          props: {
                            name: '文本输入',
                            children: '2000',
                          },
                          style: {
                            color: 'rgba(0, 0, 0, 0.3)',
                            fontSize: 11,
                          },
                          isContainer: false,
                          isBusiObjContainer: false,
                          cmdgroup: ['basic'],
                          platform: 'h5',
                          fieldProps: {
                            trigger: 'onChange',
                            valuePropName: 'children',
                          },
                          isInlineBlock: true,
                          setEvents: [],
                          icon: 'Text',
                          description: '',
                          image: '',
                          groupsName: '基础',
                          transform: {
                            value: 'children',
                          },
                          isLabelDropBoxChild: false,
                          components: [],
                          path: [
                            '454426',
                            'View_454426_1',
                            'DynamicList_686726',
                            'View_948063',
                            'View_551793',
                            'View_874017',
                            'View_293786',
                          ],
                        },
                      ],
                      path: [
                        '454426',
                        'View_454426_1',
                        'DynamicList_686726',
                        'View_948063',
                        'View_551793',
                        'View_874017',
                      ],
                    },
                    {
                      id: 'Text_6710417',
                      label: '文本输入',
                      compName: 'Text',
                      type: 'Text',
                      compType: 1,
                      compLib: 'antd-mobile',
                      props: {
                        name: '文本输入',
                        children: '2021.10.10',
                      },
                      style: {
                        color: 'rgba(0, 0, 0, 0.3)',
                        fontSize: 11,
                      },
                      isContainer: false,
                      isBusiObjContainer: false,
                      cmdgroup: ['basic'],
                      platform: 'h5',
                      fieldProps: {
                        trigger: 'onChange',
                        valuePropName: 'children',
                      },
                      isInlineBlock: true,
                      setEvents: [],
                      icon: 'Text',
                      description: '',
                      image: '',
                      groupsName: '基础',
                      transform: {
                        value: 'children',
                      },
                      isLabelDropBoxChild: false,
                      components: [],
                      path: [
                        '454426',
                        'View_454426_1',
                        'DynamicList_686726',
                        'View_948063',
                        'View_551793',
                        'View_874017',
                      ],
                    },
                  ],
                  path: [
                    '454426',
                    'View_454426_1',
                    'DynamicList_686726',
                    'View_948063',
                    'View_551793',
                  ],
                },
              ],
              path: [
                '454426',
                'View_454426_1',
                'DynamicList_686726',
                'View_948063',
              ],
            },
          ],
          path: ['454426', 'View_454426_1', 'DynamicList_686726'],
        },
      ],
      path: ['454426', 'View_454426_1'],
    },
    {
      id: 'DynamicList_2820446',
      label: '动态列表',
      compName: 'DynamicList',
      type: 'DynamicList',
      compType: 2,
      compLib: '@/components',
      props: {
        name: '动态列表',
        columnNum: 2,
        status: '1',
        styleType: 'default',
        paging: true,
        pageSize: 20,
        pageNum: 1,
        pulling: true,
        pullingText: '下拉刷新',
        canReleaseText: '松开刷新',
        refreshingText: '正在刷新',
        completeText: '刷新成功',
        dataId: 'asd',
        dataSource: '$[{id: 1},{id: 2}, {id: 3}]$',
      },
      style: {
        titleFontSize: 15,
      },
      isContainer: true,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'h5',
      engineApi: ['MemoRenderer'],
      setEvents: [],
      description: '',
      image: '',
      groupsName: '高级',
      icon: 'LoadMore',
      isLabelDropBoxChild: false,
      functors: {
        dataSource: {
          title: '$[{id: 1},{id: 2}, {id: 3}]$',
          value: '$[{  id: 1}, {  id: 2}, {  id: 3}]$',
          dependOtherIds: [],
        },
      },
      components: [
        {
          id: 'View_695851',
          label: '布局容器',
          compName: 'View',
          type: 'View',
          compType: 0,
          compLib: '@/components',
          props: {
            name: '布局容器4',
            visible: 1,
          },
          style: {
            margin: '10px 5px 0 5px',
            padding: '12px 12px 12px 12px',
            borderRadius: 8,
            backgroundColor: 'rgba(255, 255, 255, 1)',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'stretch',
          },
          isContainer: true,
          isBusiObjContainer: false,
          cmdgroup: ['basic'],
          platform: 'h5',
          engineApi: ['downloadFileByFileCode'],
          description: '',
          image: '',
          groupsName: '容器',
          icon: 'View',
          setEvents: [],
          isLabelDropBoxChild: false,
          components: [
            {
              id: 'Image_156573',
              label: '图片',
              compName: 'Image',
              type: 'Image',
              compType: 1,
              compLib: '@/components',
              props: {
                name: '图片',
                visible: 'true',
                disabled: true,
                uploadType: 'fileType',
                src: 'https://gw.alipayobjects.com/zos/rmsportal/WXoqXTHrSnRcUwEaQgXJ.png',
                srcType: 'fileCode',
              },
              style: {
                width: '100%',
                height: '124px',
                backgroundColor: 'rgba(0, 0, 0, 0.04)',
              },
              isContainer: false,
              isBusiObjContainer: false,
              cmdgroup: ['basic'],
              platform: 'h5',
              engineApi: ['downloadFileByFileCode', 'downloadByFileId', 'http'],
              isInlineBlock: true,
              setEvents: [],
              description: '',
              image: '',
              groupsName: '基础',
              icon: 'Image',
              isLabelDropBoxChild: false,
              components: [],
              path: [
                '454426',
                'View_454426_1',
                'DynamicList_2820446',
                'View_695851',
              ],
            },
            {
              id: 'View_35476',
              label: '布局容器',
              compName: 'View',
              type: 'View',
              compType: 0,
              compLib: '@/components',
              props: {
                name: '布局容器4',
                visible: 1,
              },
              style: {
                flex: 1,
                margin: '6px 0 0 0',
                padding: '0 0 0 0',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'stretch',
              },
              isContainer: true,
              isBusiObjContainer: false,
              cmdgroup: ['basic'],
              platform: 'h5',
              engineApi: ['downloadFileByFileCode'],
              description: '',
              image: '',
              groupsName: '容器',
              icon: 'View',
              setEvents: [],
              isLabelDropBoxChild: false,
              components: [
                {
                  id: 'View_845817',
                  label: '布局容器',
                  compName: 'View',
                  type: 'View',
                  compType: 0,
                  compLib: '@/components',
                  props: {
                    name: '布局容器4',
                    visible: 1,
                  },
                  style: {
                    margin: '0 0 0 0',
                    padding: '0 0 0 0',
                    display: 'flex',
                    flexDirection: 'row',
                  },
                  isContainer: true,
                  isBusiObjContainer: false,
                  cmdgroup: ['basic'],
                  platform: 'h5',
                  engineApi: ['downloadFileByFileCode'],
                  description: '',
                  image: '',
                  groupsName: '容器',
                  icon: 'View',
                  setEvents: [],
                  isLabelDropBoxChild: false,
                  components: [
                    {
                      id: 'Text_176602',
                      label: '文本输入',
                      compName: 'Text',
                      type: 'Text',
                      compType: 1,
                      compLib: 'antd-mobile',
                      props: {
                        name: '标题',
                        children: '列表标题',
                      },
                      style: {
                        fontSize: 14,
                        fontWeidht: 'bold',
                        color: 'rgba(0, 0, 0, 0.9)',
                      },
                      isContainer: false,
                      isBusiObjContainer: false,
                      cmdgroup: ['basic'],
                      platform: 'h5',
                      fieldProps: {
                        trigger: 'onChange',
                        valuePropName: 'children',
                      },
                      isInlineBlock: true,
                      setEvents: [],
                      icon: 'Text',
                      description: '',
                      image: '',
                      groupsName: '基础',
                      transform: {
                        value: 'children',
                      },
                      isLabelDropBoxChild: false,
                      components: [],
                      path: [
                        '454426',
                        'View_454426_1',
                        'DynamicList_2820446',
                        'View_695851',
                        'View_35476',
                        'View_845817',
                      ],
                    },
                  ],
                  path: [
                    '454426',
                    'View_454426_1',
                    'DynamicList_2820446',
                    'View_695851',
                    'View_35476',
                  ],
                },
                {
                  id: 'View_545794',
                  label: '布局容器',
                  compName: 'View',
                  type: 'View',
                  compType: 0,
                  compLib: '@/components',
                  props: {
                    name: '布局容器5',
                    visible: 1,
                  },
                  style: {
                    margin: '6px 0 0 0',
                    padding: '0 0 0 0',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'stretch',
                  },
                  isContainer: true,
                  isBusiObjContainer: false,
                  cmdgroup: ['basic'],
                  platform: 'h5',
                  engineApi: ['downloadFileByFileCode'],
                  description: '',
                  image: '',
                  groupsName: '容器',
                  icon: 'View',
                  setEvents: [],
                  isLabelDropBoxChild: false,
                  components: [
                    {
                      id: 'Text_8204883',
                      label: '文本输入',
                      compName: 'Text',
                      type: 'Text',
                      compType: 1,
                      compLib: 'antd-mobile',
                      props: {
                        name: '详情',
                        children:
                          '描述文案内容展示，描述文案内容展示描述文案内容展示内容展示最多展示两行',
                      },
                      style: {
                        color: 'rgba(0, 0, 0, 0.6)',
                        fontSize: 11,
                      },
                      isContainer: false,
                      isBusiObjContainer: false,
                      cmdgroup: ['basic'],
                      platform: 'h5',
                      fieldProps: {
                        trigger: 'onChange',
                        valuePropName: 'children',
                      },
                      isInlineBlock: true,
                      setEvents: [],
                      icon: 'Text',
                      description: '',
                      image: '',
                      groupsName: '基础',
                      transform: {
                        value: 'children',
                      },
                      isLabelDropBoxChild: false,
                      components: [],
                      path: [
                        '454426',
                        'View_454426_1',
                        'DynamicList_2820446',
                        'View_695851',
                        'View_35476',
                        'View_545794',
                      ],
                    },
                  ],
                  path: [
                    '454426',
                    'View_454426_1',
                    'DynamicList_2820446',
                    'View_695851',
                    'View_35476',
                  ],
                },
                {
                  id: 'View_52702',
                  label: '布局容器',
                  compName: 'View',
                  type: 'View',
                  compType: 0,
                  compLib: '@/components',
                  props: {
                    name: '布局容器6',
                    visible: 1,
                  },
                  style: {
                    margin: '6px 0 0 0',
                    padding: '0 0 0 0',
                    display: 'flex',
                    flexDirection: 'row',
                    justifyContent: 'space-between',
                  },
                  isContainer: true,
                  isBusiObjContainer: false,
                  cmdgroup: ['basic'],
                  platform: 'h5',
                  engineApi: ['downloadFileByFileCode'],
                  description: '',
                  image: '',
                  groupsName: '容器',
                  icon: 'View',
                  setEvents: [],
                  isLabelDropBoxChild: false,
                  components: [
                    {
                      id: 'View_6166974',
                      label: '布局容器',
                      compName: 'View',
                      type: 'View',
                      compType: 0,
                      compLib: '@/components',
                      props: {
                        name: '布局容器4',
                        visible: 1,
                      },
                      style: {
                        margin: '0 0 0 0',
                        padding: '0 0 0 0',
                        display: 'flex',
                        flexDirection: 'row',
                      },
                      isContainer: true,
                      isBusiObjContainer: false,
                      cmdgroup: ['basic'],
                      platform: 'h5',
                      engineApi: ['downloadFileByFileCode'],
                      description: '',
                      image: '',
                      groupsName: '容器',
                      icon: 'View',
                      setEvents: [],
                      isLabelDropBoxChild: false,
                      components: [
                        {
                          id: 'Icon_7227846',
                          label: '图标',
                          compName: 'Icon',
                          type: 'Icon',
                          compType: 1,
                          compLib: '@/components',
                          props: {
                            name: '图标',
                            state: '1',
                            mode: 'normal',
                            icon: {
                              type: 'check-circle',
                              theme: 'outlined',
                              fontAddress: '',
                              isIconFont: false,
                            },
                            size: 'sm',
                            theme: 'outlined',
                            type: {
                              type: 'eye',
                              theme: 'filled',
                              fontAddress: '',
                              isIconFont: false,
                              iconFileInfo: {},
                            },
                          },
                          style: {
                            border: '0px',
                            color: '#9b9b9b',
                            fontSize: 12,
                            margin: '0 3 0 0',
                          },
                          isContainer: false,
                          isBusiObjContainer: false,
                          cmdgroup: ['basic'],
                          platform: 'h5',
                          engineApi: [
                            'downloadFileByFileCode',
                            'getMaterialFile',
                          ],
                          isInlineBlock: true,
                          setEvents: [],
                          description: '',
                          image: '',
                          groupsName: '基础',
                          icon: 'Icon',
                          isLabelDropBoxChild: false,
                          components: [],
                          path: [
                            '454426',
                            'View_454426_1',
                            'DynamicList_2820446',
                            'View_695851',
                            'View_35476',
                            'View_52702',
                            'View_6166974',
                          ],
                        },
                        {
                          id: 'Text_757552',
                          label: '文本输入',
                          compName: 'Text',
                          type: 'Text',
                          compType: 1,
                          compLib: 'antd-mobile',
                          props: {
                            name: '文本输入',
                            children: '2000',
                          },
                          style: {
                            color: 'rgba(0, 0, 0, 0.3)',
                            fontSize: 11,
                          },
                          isContainer: false,
                          isBusiObjContainer: false,
                          cmdgroup: ['basic'],
                          platform: 'h5',
                          fieldProps: {
                            trigger: 'onChange',
                            valuePropName: 'children',
                          },
                          isInlineBlock: true,
                          setEvents: [],
                          icon: 'Text',
                          description: '',
                          image: '',
                          groupsName: '基础',
                          transform: {
                            value: 'children',
                          },
                          isLabelDropBoxChild: false,
                          components: [],
                          path: [
                            '454426',
                            'View_454426_1',
                            'DynamicList_2820446',
                            'View_695851',
                            'View_35476',
                            'View_52702',
                            'View_6166974',
                          ],
                        },
                      ],
                      path: [
                        '454426',
                        'View_454426_1',
                        'DynamicList_2820446',
                        'View_695851',
                        'View_35476',
                        'View_52702',
                      ],
                    },
                    {
                      id: 'Text_193314',
                      label: '文本输入',
                      compName: 'Text',
                      type: 'Text',
                      compType: 1,
                      compLib: 'antd-mobile',
                      props: {
                        name: '文本输入',
                        children: '2021.10.10',
                      },
                      style: {
                        color: 'rgba(0, 0, 0, 0.3)',
                        fontSize: 11,
                      },
                      isContainer: false,
                      isBusiObjContainer: false,
                      cmdgroup: ['basic'],
                      platform: 'h5',
                      fieldProps: {
                        trigger: 'onChange',
                        valuePropName: 'children',
                      },
                      isInlineBlock: true,
                      setEvents: [],
                      icon: 'Text',
                      description: '',
                      image: '',
                      groupsName: '基础',
                      transform: {
                        value: 'children',
                      },
                      isLabelDropBoxChild: false,
                      components: [],
                      path: [
                        '454426',
                        'View_454426_1',
                        'DynamicList_2820446',
                        'View_695851',
                        'View_35476',
                        'View_52702',
                      ],
                    },
                  ],
                  path: [
                    '454426',
                    'View_454426_1',
                    'DynamicList_2820446',
                    'View_695851',
                    'View_35476',
                  ],
                },
              ],
              path: [
                '454426',
                'View_454426_1',
                'DynamicList_2820446',
                'View_695851',
              ],
            },
          ],
          path: ['454426', 'View_454426_1', 'DynamicList_2820446'],
        },
      ],
      path: ['454426', 'View_454426_1'],
    },
  ],
};
