export const Table = {
  type: 'Table',
  variable: {},
  groupsName: '高级',
  icon: 'icon-ico-comp-table',
  title: '表格',
  defaultValue: [{}],
  tpl: ``,
  components: [
    {
      id: 'DynamicTable_4420557',
      label: '表格',
      compName: 'DynamicTable',
      type: 'DynamicTable',
      compType: 5,
      compLib: '@/components',
      props: {
        name: '表格',
        pagination: false,
        status: '1',
        rowKeyType: 'auto',
        bordered: 'segmentation',
        pageSize: 10,
        pageNum: 1,
        pagingStyle: 'basic',
        rowLines: 5,
        columns: [
          {
            title: '姓名',
            dataIndex: 'name',
            width: 60,
          },
          {
            title: '进度',
            dataIndex: 'sf',
            width: 100,
          },
          {
            title: '性别',
            dataIndex: 'sex',
            width: 60,
          },
          {
            title: '年龄',
            dataIndex: 'age',
            width: 50,
          },
          {
            title: '籍贯',
            dataIndex: 'jg',
            width: 70,
          },
          {
            title: '地址',
            dataIndex: 'dz',
            width: 150,
          },
        ],
        dataSource: [
          {
            name: '张三名字很长很长很长很长',
            sex: '男',
            age: '100',
            jg: '中国',
            sf: '0',
            dz: '杭州市古墩路1号',
          },
          {
            name: '李四',
            sex: 'F',
            age: '5',
            jg: '中国',
            sf: '50%',
            dz: '杭州市古墩路12号',
          },
          {
            name: '王五',
            sex: 'F',
            age: '20',
            jg: '中国',
            sf: '浙江',
            dz: '杭州市古墩路31号',
          },
          {
            name: '王五',
            sex: 'F',
            age: '26',
            jg: '中国',
            sf: '0.3',
            dz: '杭州市古墩路111号',
          },
          {
            name: '王五',
            sex: 'F',
            age: '35',
            jg: '中国',
            sf: '0.2',
            dz: '杭州市古墩路12号',
          },
          {
            name: '王四',
            sex: 'F',
            age: '35',
            jg: '中国',
            sf: '12.3',
            dz: '杭州市古墩路12号',
          },
          {
            name: '王五',
            sex: 'M',
            age: '35',
            jg: '中国',
            sf: '100',
            dz: '杭州市古墩路12号',
          },
          {
            name: '王五',
            sex: 'M',
            age: '35',
            jg: '中国',
            sf: '浙江',
            dz: '杭州市古墩路12号',
          },
          {
            name: '王五',
            sex: 'M',
            age: '35',
            jg: '中国',
            sf: '浙江',
            dz: '杭州市古墩路12号',
          },
          {
            name: '王五',
            sex: 'M',
            age: '35',
            jg: '中国',
            sf: '浙江',
            dz: '杭州市古墩路12号',
          },
          {
            name: '赵六',
            sex: 'M',
            age: '35',
            jg: '中国',
            sf: '浙江',
            dz: '杭州市古墩路12号',
          },
          {
            name: '王五',
            sex: 'M',
            age: '35',
            jg: '中国',
            sf: '0.01',
            dz: '杭州市古墩路12号',
          },
          {
            name: '王五',
            sex: 'M',
            age: '35',
            jg: '中国',
            sf: '0.8',
            dz: '杭州市古墩路12号',
          },
          {
            name: '王五',
            sex: 'M',
            age: '35',
            jg: '中国',
            sf: '浙江',
            dz: '杭州市古墩路12号',
          },
          {
            name: '王五',
            sex: 'M',
            age: '35',
            jg: '中国',
            sf: '浙江',
            dz: '杭州市古墩路12号',
          },
        ],
        dataSourceLoading: false,
        showHead: true,
        tableTitle: '分割线表格',
      },
      style: {
        titleBackground: '#FAFAFA',
        titleColor: 'rgba(28, 36, 46, 0.55)',
        leftTitleColor: '#1C242E',
        width: '100%',
        height: '300px',
        borderRadius: '8px 8px 8px 8px',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'h5',
      setEvents: [],
      icon: 'DynamicTable',
      description: '',
      groupsName: '高级',
      engineApi: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['454426', 'View_454426_1'],
    },
  ],
};
