export const Button = {
  type: 'Button',
  variable: {
    textColor: { type: 'color', label: '文本颜色', groupsName: '文字' },
    lineHeight: { type: 'px', label: '文本行高', groupsName: '文字' },
    fontSize: { type: 'px', label: '文本尺寸', groupsName: '文字' },
    backgroundColor: {
      type: 'color',
      label: '背景颜色',
      groupsName: '背景颜色',
    },
    borderColor: { type: 'color', label: '边框颜色', groupsName: '边框' },
    borderRadius: { type: 'px', label: '边框圆角', groupsName: '边框' },
    paddingValue: { type: 'marginInput', label: '内边距', groupsName: '布局' },
    marginValue: { type: 'marginInput', label: '外边距', groupsName: '布局' },
  },
  groupsName: '通用',
  icon: 'Button',
  title: '按钮',
  defaultValue: [
    {
      textColor: '#1c242e',
      lineHeight: '0px',
      fontSize: '14px',
      backgroundColor: '#fff',
      borderColor: '#D8E0EC',
      borderRadius: '8px',
      paddingValue: '4px 24px 4px 24px',
      marginValue: '0px',
    },
  ],
  tpl: `.ued-button-wrap.pcfactory-btn {
        color: textColor;
        line-height: lineHeight;
        font-size: fontSize;
        background-color: backgroundColor;
        border-color: borderColor;
        border-radius: borderRadius;
        padding: paddingValue;
        margin: marginValue;
      }
    `,
  components: [
    {
      id: 'Button_726243',
      label: '按钮',
      compName: 'Button',
      type: 'Button',
      compType: 1,
      compLib: 'comm',
      props: {
        name: '按钮',
        basicStatus: 1,
        classification: 'default',
        autoProcessFlow: false,
        flowProcessResult: 'common',
        iconPosition: 'left',
        ghost: false,
        block: false,
        size: 'default',
        disabled: false,
        type: 'primary',
        btnIcon: 'none',
        hasIcon: false,
        shape: 'default',
        loading: false,
        btnText: '按钮',
      },
      style: {
        textAlign: 'center',
        fontSize: 14,
        fontWeight: 400,
        height: '32px',
        color: '#FFF',
        borderSetting: 'border 1px solid ',
        backgroundColor: '',
        border: '1px solid ',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Button',
      description: '',
      image: '',
      groupsName: '通用',
      isInlineBlock: true,
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['8485714', 'View_8485714_1'],
    },
    {
      id: 'Button_4610898',
      label: '按钮',
      compName: 'Button',
      type: 'Button',
      compType: 1,
      compLib: 'comm',
      props: {
        name: '按钮',
        basicStatus: 1,
        classification: 'default',
        autoProcessFlow: false,
        flowProcessResult: 'common',
        iconPosition: 'left',
        ghost: false,
        block: false,
        size: 'default',
        disabled: false,
        type: 'default',
        btnIcon: 'none',
        hasIcon: false,
        shape: 'default',
        loading: false,
        btnText: '按钮',
      },
      style: {
        textAlign: 'center',
        fontSize: 14,
        fontWeight: 400,
        height: '32px',
        color: '#1C242E',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Button',
      description: '',
      image: '',
      groupsName: '通用',
      isInlineBlock: true,
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['8485714', 'View_8485714_1'],
    },
    {
      id: 'Button_03196897',
      label: '按钮',
      compName: 'Button',
      type: 'Button',
      compType: 1,
      compLib: 'comm',
      props: {
        name: '按钮',
        basicStatus: 1,
        classification: 'default',
        autoProcessFlow: false,
        flowProcessResult: 'common',
        iconPosition: 'left',
        ghost: false,
        block: false,
        size: 'default',
        disabled: false,
        type: 'dashed',
        btnIcon: 'none',
        hasIcon: false,
        shape: 'default',
        loading: false,
        btnText: '按钮',
      },
      style: {
        textAlign: 'center',
        fontSize: 14,
        fontWeight: 400,
        height: '32px',
        color: '#1C242E',
        borderSetting: 'border 1px dashed #E5E5E5',
        backgroundColor: '#FFF',
        border: '1px dashed #E5E5E5',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Button',
      description: '',
      image: '',
      groupsName: '通用',
      isInlineBlock: true,
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['8485714', 'View_8485714_1'],
    },
    {
      id: 'Button_060837',
      label: '按钮',
      compName: 'Button',
      type: 'Button',
      compType: 1,
      compLib: 'comm',
      props: {
        name: '按钮',
        basicStatus: 1,
        classification: 'default',
        autoProcessFlow: false,
        flowProcessResult: 'common',
        iconPosition: 'left',
        ghost: false,
        block: false,
        size: 'default',
        disabled: false,
        type: 'text',
        btnIcon: 'none',
        hasIcon: false,
        shape: 'default',
        loading: false,
        btnText: '按钮',
      },
      style: {
        textAlign: 'center',
        fontSize: 14,
        fontWeight: 400,
        height: '32px',
        color: '#1C242E',
        borderSetting: '',
        backgroundColor: '#FFF',
        border: '',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Button',
      description: '',
      image: '',
      groupsName: '通用',
      isInlineBlock: true,
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['8485714', 'View_8485714_1'],
    },
    {
      id: 'Button_534879',
      label: '按钮',
      compName: 'Button',
      type: 'Button',
      compType: 1,
      compLib: 'comm',
      props: {
        name: '按钮',
        basicStatus: 1,
        classification: 'default',
        autoProcessFlow: false,
        flowProcessResult: 'common',
        iconPosition: 'left',
        ghost: false,
        block: false,
        size: 'default',
        disabled: false,
        type: 'link',
        btnIcon: 'none',
        hasIcon: false,
        shape: 'default',
        loading: false,
        btnText: '按钮',
      },
      style: {
        textAlign: 'center',
        fontSize: 14,
        fontWeight: 400,
        height: '32px',
        color: '#47E',
        borderSetting: '',
        backgroundColor: '',
        border: '',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Button',
      description: '',
      image: '',
      groupsName: '通用',
      isInlineBlock: true,
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['8485714', 'View_8485714_1'],
    },
  ],
};
