export const Link = {
  type: 'Link',
  variable: {
    textColor: { type: 'color', label: '文本颜色', groupsName: '文字' },
    // TODO: 行高默认写死
    // lineHeight: { type: 'px', label: '文本行高', groupsName: '文字' },
    fontSize: { type: 'px', label: '文本尺寸', groupsName: '文字' },
  },
  groupsName: '通用',
  icon: 'Link',
  title: '超链接',
  defaultValue: [
    {
      textColor: '#1890ff',
      lineHeight: '0px',
      fontSize: '14px',
    },
  ],
  tpl: `.ued-link {
      color: textColor;
      line-height: lineHeight;
      font-size: fontSize;
    }`,
  components: [
    {
      id: 'Link_610976',
      label: '超链接',
      compName: 'Link',
      type: 'Link',
      compType: 1,
      compLib: 'comm',
      props: {
        name: '超链接',
        target: '_self',
        basicStatus: 1,
        linkValue: '超链接',
      },
      style: {},
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Link',
      description: '',
      image: '',
      groupsName: '通用',
      isInlineBlock: true,
      engineApi: ['service.downloadByFileId'],
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['839512', 'View_839512_1'],
    },
    {
      id: 'View_640324',
      label: '普通容器',
      compName: 'View',
      type: 'View',
      compType: 0,
      compLib: 'custom',
      props: {
        name: '普通容器1',
        basicStatus: 1,
      },
      style: {
        textAlign: 'left',
        display: 'block',
        flexDirection: 'column',
        padding: '0px 0px 0px 0px',
        width: '100%',
        backgroundColor: '#FFFFFF',
      },
      isContainer: true,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'View',
      description: '',
      image: '',
      groupsName: '布局',
      engineApi: ['service.downloadFileByFileCode'],
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [
        {
          id: 'Link_531499',
          label: '超链接',
          compName: 'Link',
          type: 'Link',
          compType: 1,
          compLib: 'comm',
          props: {
            name: '超链接',
            target: '_self',
            basicStatus: 1,
            linkValue: '超链接1',
          },
          style: {},
          isContainer: false,
          isBusiObjContainer: false,
          cmdgroup: ['basic'],
          platform: 'pc',
          icon: 'Link',
          description: '',
          image: '',
          groupsName: '通用',
          isInlineBlock: true,
          engineApi: ['service.downloadByFileId'],
          setEvents: [],
          isLabelDropBoxChild: false,
          components: [],
          path: ['839512', 'View_839512_1', 'View_640324'],
        },
      ],
      path: ['839512', 'View_839512_1'],
    },
  ],
};
