export const Switch = {
  type: 'Switch',
  variable: {
    labelTextColor: {
      type: 'color',
      label: '标签文本颜色',
      groupsName: '文字',
      desc: '继承自表单，此处不可编辑',
      canEdit: false,
      extendsKey: 'Form',
    },
    labelLineHeight: {
      type: 'px',
      label: '标签文本行高',
      groupsName: '文字',
      desc: '继承自表单，此处不可编辑',
      canEdit: false,
      extendsKey: 'Form',
    },
    labelFontSize: {
      type: 'px',
      label: '标签文本尺寸',
      groupsName: '文字',
      desc: '继承自表单，此处不可编辑',
      canEdit: false,
      extendsKey: 'Form',
    },
    openColor: {
      type: 'color',
      label: '开启颜色',
      groupsName: '文字',
    },
    closeColor: {
      type: 'color',
      label: '关闭颜色',
      groupsName: '文字',
    },
  },
  groupsName: '数据录入',
  icon: 'icon-ico-comp-switch',
  title: '开关',
  defaultValue: [
    {
      openColor: '#47e',
      closeColor: 'rgba(28,36,46,.25)',
    },
  ],
  tpl: `.pcfactory-switch {
      background-color: closeColor;
    }
    .pcfactory-switch-checked {
      background-color: openColor;
    }`,
  components: [
    {
      id: 'Form_180373',
      label: '表单',
      compName: 'Form',
      type: 'Form',
      compType: 0,
      compLib: 'comm',
      props: {
        name: '表单',
        colSpan: 12,
        labelCol: 8,
        wrapperCol: 16,
        layout: 'vertical',
        colon: true,
        labelAlign: 'right',
        basicStatus: 1,
        colSpace: 16,
        rowSpace: 16,
        formCode: 'Code_Form_180373',
      },
      style: {
        padding: '0px 0px 0px 0px',
      },
      isContainer: true,
      isBusiObjContainer: true,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Form',
      description: '',
      image: '',
      groupsName: '容器',
      engineApi: [
        'service.downloadFileByFileCode',
        'getVisible',
        'stateListener',
      ],
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [
        {
          id: 'Switch_088117',
          label: '开关',
          compName: 'Switch',
          type: 'Switch',
          compType: 2,
          compLib: 'comm',
          props: {
            name: '开关',
            size: 'default',
            labelCol: 8,
            wrapperCol: 16,
            basicStatus: 1,
            titleTip: 'notext',
            tipSize: 'default',
            tipWidth: '240px',
            tipHeight: 'auto',
            switchStyle: 'none',
            checkedChildren: '开启',
            unCheckedChildren: '关闭',
            checkedChildrenIcon: {
              type: 'check',
              theme: 'outlined',
              isIconFont: false,
            },
            unCheckedChildrenIcon: {
              type: 'close',
              theme: 'outlined',
              isIconFont: false,
            },
            required: false,
            defaultChecked: false,
            formItemIndex: 10,
            fieldName: 'vxc',
          },
          style: {},
          isContainer: false,
          isBusiObjContainer: false,
          cmdgroup: ['basic'],
          platform: 'pc',
          fieldProps: {
            trigger: 'onChange',
            valuePropName: 'value',
          },
          icon: 'Switch',
          description: '',
          image: '',
          groupsName: '数据录入',
          isInlineBlock: true,
          setEvents: [],
          isLabelDropBoxChild: false,
          components: [],
          path: ['998509', 'Form_180373'],
        },
      ],
      path: ['998509'],
    },
  ],
};
