export const Tag = {
  type: 'Tag',
  variable: {
    // tagHeight: { type: 'px', label: '标签高度', groupsName: '文字' },
    backgroundColor: {
      type: 'color',
      label: '背景颜色',
      groupsName: '背景颜色',
    },
    paddingValue: { type: 'marginInput', label: '内边距', groupsName: '布局' },
    // borderColor: { type: 'color', label: '边框颜色', groupsName: '边框' },
    borderRadius: { type: 'px', label: '边框圆角', groupsName: '边框' },
    // textColor: { type: 'color', label: '文本颜色', groupsName: '文字' },
    fontSize: { type: 'px', label: '文本尺寸', groupsName: '文字' },
    closeColor: { type: 'color', label: '关闭图标颜色', groupsName: '文字' },
    closeSize: { type: 'px', label: '关闭图标尺寸', groupsName: '文字' },
  },
  groupsName: '数据展示',
  icon: 'icon-ico-comp-tag',
  title: '标签',
  defaultValue: [
    {
      backgroundColor: 'rgba(0,0,0,0)',
      paddingValue: '0 7px 0 7px',
      borderRadius: '11px',
      fontSize: '12px',
      closeColor: 'rgba(0,0,0,.45)',
      closeSize: '10px',
    },
  ],
  tpl: `.ued-tag-wrap .pcfactory-tag{
    background: backgroundColor;
    padding: paddingValue;
    border-radius: borderRadius;
    font-size: fontSize;
  }
  .ued-tag-wrap .pcfactory-tag .pcfactory-tag-close-icon { 
    color: closeColor;
    > svg{
      width: closeSize;
      height: closeSize;
    }
  }`,
  components: [
    {
      id: 'Tag_6939955',
      label: '标签',
      compName: 'Tag',
      type: 'Tag',
      compType: 3,
      compLib: 'antd',
      props: {
        name: '标签',
        basicStatus: 1,
        title: 'tag',
        closable: true,
        tagType: {
          name: 'tag',
          key: '1',
        },
      },
      style: {
        minHeight: '10px',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Tag',
      description: '',
      image: '',
      groupsName: '数据展示',
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['3602564', 'View_3602564_1'],
    },
    {
      id: 'Tag_099399',
      label: '标签',
      compName: 'Tag',
      type: 'Tag',
      compType: 3,
      compLib: 'antd',
      props: {
        name: '标签',
        basicStatus: 1,
        title: 'tag',
        closable: true,
        tagType: {
          name: '蓝色描边标签',
          key: '2',
          classname: 'ued-tag-blue',
        },
      },
      style: {
        minHeight: '10px',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Tag',
      description: '',
      image: '',
      groupsName: '数据展示',
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['3602564', 'View_3602564_1'],
    },
    {
      id: 'Tag_22958',
      label: '标签',
      compName: 'Tag',
      type: 'Tag',
      compType: 3,
      compLib: 'antd',
      props: {
        name: '标签',
        basicStatus: 1,
        title: 'tag',
        closable: true,
        tagType: {
          name: '紫色描边标签',
          key: '3',
          classname: 'ued-tag-purple',
        },
      },
      style: {
        minHeight: '10px',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Tag',
      description: '',
      image: '',
      groupsName: '数据展示',
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['3602564', 'View_3602564_1'],
    },
    {
      id: 'Tag_799551',
      label: '标签',
      compName: 'Tag',
      type: 'Tag',
      compType: 3,
      compLib: 'antd',
      props: {
        name: '标签',
        basicStatus: 1,
        title: 'tag',
        closable: true,
        tagType: {
          name: '绿色描边标签',
          key: '4',
          classname: 'ued-tag-green',
        },
      },
      style: {
        minHeight: '10px',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Tag',
      description: '',
      image: '',
      groupsName: '数据展示',
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['3602564', 'View_3602564_1'],
    },
    {
      id: 'Tag_10752956',
      label: '标签',
      compName: 'Tag',
      type: 'Tag',
      compType: 3,
      compLib: 'antd',
      props: {
        name: '标签',
        basicStatus: 1,
        title: 'tag',
        closable: true,
        tagType: {
          name: '红色描边标签',
          key: '5',
          classname: 'ued-tag-red',
        },
      },
      style: {
        minHeight: '10px',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Tag',
      description: '',
      image: '',
      groupsName: '数据展示',
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['3602564', 'View_3602564_1'],
    },
    {
      id: 'Tag_3207935',
      label: '标签',
      compName: 'Tag',
      type: 'Tag',
      compType: 3,
      compLib: 'antd',
      props: {
        name: '标签',
        basicStatus: 1,
        title: 'tag',
        closable: true,
        tagType: {
          name: '橙色描边标签',
          key: '6',
          classname: 'ued-tag-orange',
        },
      },
      style: {
        minHeight: '10px',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Tag',
      description: '',
      image: '',
      groupsName: '数据展示',
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['3602564', 'View_3602564_1'],
    },
    {
      id: 'Tag_905984',
      label: '标签',
      compName: 'Tag',
      type: 'Tag',
      compType: 3,
      compLib: 'antd',
      props: {
        name: '标签',
        basicStatus: 1,
        title: 'tag',
        closable: true,
        tagType: {
          name: '金色描边标签',
          key: '7',
          classname: 'ued-tag-gold',
        },
      },
      style: {
        minHeight: '10px',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Tag',
      description: '',
      image: '',
      groupsName: '数据展示',
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['3602564', 'View_3602564_1'],
    },
    {
      id: 'Tag_0175',
      label: '标签',
      compName: 'Tag',
      type: 'Tag',
      compType: 3,
      compLib: 'antd',
      props: {
        name: '标签',
        basicStatus: 1,
        title: 'tag',
        closable: true,
        tagType: {
          name: '青色描边标签',
          key: '8',
          classname: 'ued-tag-cyan',
        },
      },
      style: {
        minHeight: '10px',
      },
      isContainer: false,
      isBusiObjContainer: false,
      cmdgroup: ['basic'],
      platform: 'pc',
      icon: 'Tag',
      description: '',
      image: '',
      groupsName: '数据展示',
      setEvents: [],
      isLabelDropBoxChild: false,
      components: [],
      path: ['3602564', 'View_3602564_1'],
    },
  ],
};
